### PR TITLE
fix C++ build errors on macOS

### PR DESCRIPTION
**Pull request by PatTheMav**
Fixes https://github.com/Andersama/rematrix-filter/issues/6 and more follow-up build errors.

Void pointers must be explicitly typecast to their target types in C++ (while it will compile in C).

Also `compare_exchange_strong` expects l-values, so I just store the values and pass them accordingly.

Last but not least I'm unsure about the explicit typecast of `route[c]` to `int`, but it seems to work fine so far.

### CODE REVIEW

**Comment by Andersama** [comment]
I wouldn't worry about any of these issues since a less strict compiler allowed me to build and get exactly what was needed just fine, an array access gets compiled down into some form of lea instruction anyway. Though I have to wonder about the atomics header bit, not sure how I missed that, that's definitely a compiler error.

**Comment by PatTheMav** [comment]
Well on macOS there’s more or less only `clang` and it’s applying C++ language rules hard. All those fixes were needed to get it to compile in the first place - there are still warnings, but the resulting library works fine on macOS so far. 😄

**Comment by Andersama** [comment]
Well there's more statically checked things now that more or less aren't errors, but are the root of most bugs I bet if I went back to rebuild I'd be getting compiler errors as well. I'm puzzled on how I got through without the atomics header.

I have a message on the forum from someone who wanted a mac build. Weird timing, unless that was you.

**Comment by PatTheMav** [comment]
There was another one on Discord as well, that’s why I sat down and tried to compile it. I’ll release the fixed version in my fork later today, will comment here once the deed is done.

**Pull request merged**
